---
- name: Add MySQL Apt Key
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: A4A9406876FCBD3C456770C88C718D3B5072E1F5
    state: present

- name: Add MySQL Repository
  become: yes
  shell: echo "deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7" | sudo tee /etc/apt/sources.list.d/mysql.list

- name: mysql | Set root Password
  debconf:
    name: mysql-community-server
    question: 'mysql-community-server/root-pass'
    value: '{{ mysql.root_password }}'
    vtype: password

- name: mysql | Set root Password Again
  debconf:
    name: mysql-community-server
    question: 'mysql-community-server/re-root-pass'
    value: '{{ mysql.root_password }}'
    vtype: password

- name: mysql | Install MySQL Packages
  become: yes
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: true
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
