---



- name: mysql | Set root Password
  debconf:
    name: mysql-server
    question: 'mysql-server/root-pass'
    value: '' # Set as a variable
    vtype: password

- name: mysql | Set root Password Again
  debconf:
    name: mysql-server
    question: 'mysql-server/re-root-pass'
    value: '' # Set as a variable
    vtype: password

- name: mysql | Install MySQL Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
