- name: Install php-cli
  sudo: yes
  apt: pkg=php7.0-cli state=latest

- name: ensure timezone is set in cli php.ini
  lineinfile: dest='/etc/php/7.0/cli/php.ini'
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'

- name: Install php-fpm
  sudo: yes
  apt: pkg=php7.0-fpm state=latest

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = www-data'"

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?listen.group' line='listen.group = www-data'"

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
  notify: restart php-fpm

- name: ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php/7.0/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'

- name: ensure memory limit is 1024M php.ini
  lineinfile: dest='/etc/php/7.0/fpm/php.ini'
              regexp='memory_limit ='
              line='memory_limit = 1024M'

- name: Enable xdebug
  sudo: yes
  template: src=20-xdebug.ini dest=/etc/php/7.0/fpm/conf.d/20-xdebug.ini
  notify: restart php-fpm

- name: Disable xdebug for CLI
  sudo: yes
  file: path=/etc/php7.0/cli/conf.d/20-xdebug.ini state=absent

- name: Install Package
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: pecl_packages

- name: Create extension .ini file
  template: >
    src="extension.tpl"
    dest="/etc/php/mods-available/{{ item }}.ini"
    owner="root"
    group="root"
    mode=0644
  with_items: pecl_packages

- name: Enable extesion on cli
  file:
    src: "/etc/php/mods-available/{{ item }}.ini"
    dest: "/etc/php/7.0/cli/conf.d/20-{{ item }}.ini"
    state: link
  with_items: pecl_packages

- name: Enable extesion on fpm
  file:
    src: "/etc/php/mods-available/{{ item }}.ini"
    dest: "/etc/php/7.0/fpm/conf.d/20-{{ item }}.ini"
    state: link
  with_items: pecl_packages
