---
- name: mongo | Import the public key used by the package management system
  become: yes
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

- name: mongo | Create a list file for MongoDB
  become: yes
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

- name: mongo | Install Mongodb Packages
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - mongodb-org
