---
- name: Add NGINX PPA Repository
  become: yes
  apt_repository: repo='ppa:nginx/stable'

- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  become: yes
  template: src={{ ws_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_file }}
  notify: restart nginx

- name: Update the vagrant user permissions
  become: yes
  shell: usermod -a -G www-data vagrant
