---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  sudo: yes
  template: src={{ ws_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_file }}
  notify: restart nginx

- name: Update the vagrant user permissions
  sudo: yes
  shell: usermod -a -G www-data vagrant
