---
- hosts: all
  become: true
  vars:
    web_server: nginxphp
    servername: php56box.vb 10.10.10.11
    timezone: Europe/Berlin
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - vars/nginxphp.yml
  roles:
    - init
    - php
    - nginx
    - mysql
    - mongodb
    - composer
